#server:
#  servlet:
#    session:
#      timeout: 30m
#  port: 8082
spring:
#  profiles:
#    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5532/whmgu
    username: whmgu
    password: A123456b
    driver-class-name: org.postgresql.Driver

  jpa:
    generate-ddl: true
#    generate-ddl: false
    hibernate:
#      ddl-auto: none
      ddl-auto: create
      naming:
        implicit-strategy: ru.vgoudk.workhours.model.HumanReadableNamingStrategy
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          batch_size: 100
    show-sql: false