spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./db/whmgu;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
    username: sa
    password:
  jpa:
    database-platform: ru.vgoudk.workhours.repositories.ImprovedH2Dialect
    hibernate:
      ddl-auto: update
        #naming:
      #implicit-strategy: ru.vgoudk.workhours.model.HumanReadableNamingStrategy
  h2:
    console:
      enabled: true
      path: /h2
