spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/whmgu
    username: whmgu
    password: A123456b
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: update
        #naming:
      #implicit-strategy: ru.vgoudk.workhours.model.HumanReadableNamingStrategy
